export const AuthConfig = {
  appId: '0b2c3448-8e0a-4a54-9e79-5ba83b7b2459',
  appScopes: [
    'openid',
    'offline_access',
    'profile',
    'User.Read',
    'User.ReadBasic.All',
    'People.Read',
    'People.Read.All',
    'Sites.Read.All',
    'Sites.ReadWrite.All',
     'User.Read.All',
      'User.ReadWrite',
       'User.ReadWrite.All',
    'MailboxSettings.Read',
    'Calendars.ReadWrite',
    'GroupMember.Read.All', 
    'Group.Read.All', 
    'Directory.Read.All', 
   // 'Group.ReadWrite.All', 
    'Directory.ReadWrite.All',
     'Directory.AccessAsUser.All',
    // 'ChannelMessage.Read.All',
     'Files.ReadWrite.All',
     'Files.ReadWrite',
     'Files.Read.All',
     'Files.Read',
     'Files.Read.Selected',
     'Files.ReadWrite.AppFolder',
     'User.ManageIdentities.All','Tasks.ReadWrite','Mail.Read',
     'Device.Read.All',
     //'Mail.ReadWrite',
    // 'MailboxSettings.Read',
     'Mail.Send',
     'DelegatedPermissionGrant.ReadWrite.All',
     
  ]
};
